# Generated by Django 4.1.6 on 2023-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_discripton_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='discripton',
            field=models.TextField(max_length=1500),
        ),
    ]
