# Generated by Django 4.1.6 on 2023-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
